apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      broker:
        addresses:
        - 192.168.0.242:9092
        - 192.168.0.222:9092
        - 192.168.0.66:9092
