apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- job.yaml
commonLabels:
  component: sync-repo-file-job
nameSuffix: -sync-repo-file-job
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/sync-repo-file-job
  newTag: main-f83e60a
