apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - ascend
      cla_label_yes: ascend-cla/yes
      cla_label_no: ascend-cla/no
      check_url: https://clasign.osinfra.cn/api/v1/individual-signing/gitee/ascend
      sign_url: https://clasign.osinfra.cn/sign/Z2l0ZWUlMkZhc2NlbmQ=
      faq_url: https://github.com/opensourceways/test-infra/blob/sync-5-22/prow/gitee-plugins/cla/faq/check-by-author/faq.md
