apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - ascend/playground
      - ascend/pyge
      - ascend/slurm-atlas-plugin
      - ascend/ascend-docker-image
      - ascend/ascend-deployer
      - ascend/tools
      - ascend/community
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."
       
      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."
       
      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."

    - repos:
      - ascend/canndev
      merge_method: squash
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."
       
      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."
       
      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."
       
      - label: ci-pipeline-passed
        person: turing_project
        tips_if_missing: "Please wait for the CI test to be completed."
        tips_if_added_by_others: "You can't add ci-pipeline-passed label manually. Please remove it and wait for the CI test to be completed."  

    - repos:
      - ascend/metadef
      - ascend/parser
      - ascend/tensorflow
      - ascend/cann-benchmark
      - ascend/ais-bench
      - ascend/atlasboost
      - ascend/cann
      - ascend/ci
      - ascend/docs
      - ascend/docs-dev
      - ascend/mindstudio
      - ascend/mindxdl-deploy
      - ascend/modelzoo
      - ascend/pytorch
      - ascend/pytorch-develop
      - ascend/samples
      - ascend/testframework
      - ascend/apex
      - ascend/apex-develop
      - ascend/mindxsdk-referenceapps
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."

      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."

      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."

      - label: ci-pipeline-passed
        tips_if_missing: "Please wait for the CI test to be completed."
        person: turing_project
        tips_if_added_by_others: "You can't add ci-pipeline-passed label manually. Please remove it and wait for the CI test to be completed."
