apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: secret-robot-token
spec:
  name: secret-robot-token
  keysMap:
    robot-token:
      path: secrets/data/mindspore/robot-gitee
      key: robot-edahelper-token
