apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- ingress.yaml
- secrets.yaml
- service.yaml
commonLabels:
  component: sync-agent
nameSuffix: -sync-agent
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee
