apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: hook-delivery
        args:
        - --port=8888
        - --config-file=/app/conf/robot-github/app_config/config.yaml
        - --hmac-secret-file=/app/conf/robot-github/hmac
        - --topic=github-webhook-openeuler
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /app/conf/robot-github/hmac
          subPath: webhook-hmac
          name: secret-volume
        - mountPath: /app/conf/robot-github/app_config/
          name: app-config
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-hook-delivery
      - name: app-config
        configMap:
          name: configmap-hook-delivery
