apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config:
      repos:
      - mindspore
      merge_remind_intervals: 30
      maximum_open_time: 90
      concurrent_size: 200
